name: gMod CI Pipeline

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        targetplatform: [x86]

    runs-on: windows-latest

    env:
      Configuration: Release
      Actions_Allow_Unsecure_Commands: true

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        echo "VCPKG_ROOT=$(pwd)\vcpkg" >> $GITHUB_ENV
        echo "PATH=$(pwd)\vcpkg;$PATH" >> $GITHUB_ENV

    - name: Build CMake Files with vcpkg toolchain
      run: cmake --preset=vcpkg

    - name: Build binaries
      run: cmake --build build --config Release
